# Generated by Django 3.0.5 on 2020-06-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200626_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcorporate',
            name='Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dcorporate',
            name='address',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dcorporate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
