# Generated by Django 3.0.5 on 2020-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_dbirthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='specialupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='specialupload/')),
            ],
        ),
    ]
