# Generated by Django 3.0.5 on 2020-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
